language: node_js
node_js:
- 12
deploy:
  - provider: npm
    email: mahmoud.salmi@msweb.net
    api_key:
      secure: eWkS6M6cV7n5ox26qg+l0KWuE5qsvwJiWQZ7gKxkxV8OYvIekNTIag96GLR0F+RpD5/AOHfN/UxznT/zWuuxnmWnCxK2x8+dc6ldSRnHZVMhRawXFq+rQ1KwUf1mRx4eU+vNC57ZapUyAUdUhAe1jiWhhlvQ0aPh4+bite5GMzOfVN2Xb2eTkqsH5xiK2hfT3F2EiFBgJ4VzYO/8fdogsh142b9RR9IWGs9ylQbILblYrgoWcvlD1agBL051MEzXCGdTzJMlifyNn4U2jcCMNUCeAIwmM1qKaBEYhu8MyIT1nXhW1eTCBiXgTkbyLqTMwkPyYgqMStiqJv4qCc15UIYq1jKiKn1LSSVk8fe30zgicheeNqiJPX1UVZKWByf7VqenKdG2uDIzUJoESy/QqQLXBUbqai7nPdtFi4R7uDlR0YXTWACM+cRz2C+7NKH49KsIor6s9xElTPQK2hTDRaN0GLpSHvbaJxjWFfUdxpTzgNf59LcwYGf15p3tkjwbKAw/3kUe5ApqIx/0W7Qj8SL/t38aJNAHFtkwNVxeEWfsH839+x1NYIh1sO4ZFgvkJ1JSCma7/c4JYB/i6PrcD+Uz1Meh2JmVQvg4nj7JH7T0ylrTz74wGYEEsVsYq10bnij2rjFTwoVYI/oRNpHzmnigtgWfV0HWj9nSfRXwTQs=
    on:
      tags: true
      repo: mahmoudsalmi/dynu-ddns-updater
    skip_cleanup: 'true'
  - provider: releases
    email: mahmoud.salmi@msweb.net
    file_glob: true
    file: "{YOURLIB}-*.tgz"
    skip_cleanup: true
    on:
      tags: true


      deploy:
        provider: npm
        email: mahmoud.salmi@msweb.net
        api_key:
          secure: Q9vbi46i72llfMrnhr+iE8jnZzKZotG9DfpJ5dKbNG7Roy90TFj1REMhylREQ9ThNe8egkZezHSciLQ0xN0smL+9D4qH4acx9oLR+TcMDsYYxDNHsuxXKn8VnqYZ0cBD8LlB0fZKX8qb+rCyxGdNkLanh9X6SbR/cg+T6fJnU/6frFjzKUg/7YYjzp1zGTfG2XyjvHtFvc0QnYo0uvZ/ZiOpIihjO+GOrvR3THxJjLy7mbkRSjDmo5MBmal0Mnx0T0bHx983bClKF2asxpD3qdasHinu9P2cijKn/QpLyhyuRJ30LM2eVHSp7yXP01y0qEP2QX69U4C4LRLKmf5giOTkRVxsyVtBcWNFJWGJ3NB0NUiVZzcjZDlHxcAFYLCcqaygN/f4mzTT/XO0LqyDkfoQhpQsMCjNkisHEbaDi47fygeaK/OR12wj7fr2jZd880SNEXEfvZCxBCJVixdGjygN8xnVfN11UECaB4z3kr/bkHSyecCErFMjvatDo0HrdKZ1+JQQJRW0hHRKWRfCirDl4lIykm7+Pg+43OmTXUFmUfJVKLUwF++hG4yna2b0BYPZ9FwGvLb7swyCWRY9GoFIZ+W4cibfJfwVJjnIq/hCp+pRKiiMdK3hoHNWP3oXV4rGiwD7dZr6N6nw5+02fF3Hb6cRMh7H0ALt82Pb+yw=
        on:
          tags: true
          repo: mahmoudsalmi/dynu-ddns-updater
        skip_cleanup: 'true'

